# Generated by Django 5.2.4 on 2025-08-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('birth_date', models.DateField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
